### ISSUE TITLE
Error loading this resource when try to playback recording from non-Chrome browsers

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#346]
Freshdesk Ticket ID: <a href='https://support.bluecherrydvr.com/helpdesk/tickets/1510' target='_blank'>1510</a> <br/> Freshdesk Ticket Agent: Unassigned<br/>Freshdesk Ticket Agent Email: Unavailable<br/>Ticket Priority: Low<br/>Freshdesk Ticket Description:<div dir="ltr">
<div>When I open the web interface, select Playback and select any video to playback, when I press tha play icon in the centre of the video, a red message appears in top left of video screen saying "Error loading this resource" and the video does not play.</div>
<div><br></div>
<div>I can click Download MP4 file and that doe let me download and play the recording, but I would like to be able to play directly from the browser.</div>
<div><br></div>
<div>This occurs on an iMac with Safari and on Android with a Dolphin browser. It does not occur on Windows 10 mmachine with Chrome browser. That works.</div>
<div><br></div>
</div> <br/>

**Comment by k3dar** [comment]
i have same error, bluecherry installed on Xubuntu 18.04.2, on same machine run browser (try Firefox, Chromium, Chrome) and only first record after add cam is played, this have size ~100MB, others (splited after 15m) have size ~460MB, then i think problem is in bigger size

**Comment by k3dar** [comment]
now try also in Windows10 + Chrome and same error, if play record, then show in topleft part of "video": Error loading this resource

**Comment by k3dar** [comment]
headers from W10+Chrome:
First record ~100MB Play OK: https://pastebin.com/N2WBY2PN
Others record ~460MB NOT Play: https://pastebin.com/W8ZwXSc0
