### ISSUE TITLE
ONVIF S support

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#360]
ONVIF S has many interesting features, the most important is motion detection on the edge device (IP camera)

**Comment by jonofmac** [comment]
This is a big feature that I'd love to have :) For lower powered machines, allowing the edge devices to use their built in hardware motion detection significantly helps the system load.

**Comment by nvsystems** [comment]
That would be very useful to support proper power saving for the recording server.
