### ISSUE TITLE
Web playback fails

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#365]
Playback fails with Error loading this resource

**Comment by antonsviridenko** [comment]
"'aresample' filter not present, cannot convert audio formats.Error opening filters!"

**Comment by antonsviridenko** [comment]
should be fixed by https://github.com/bluecherrydvr/bluecherry-apps/commit/953e42a17e5bee2c2a4735062f9d6b1cc0a58d3e
