### ISSUE TITLE
Instructions on how to change permissions disappears too quickly

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#368]
Instead of using the AJAX pop-up warning embed the instructions on the page so users can cut and paste instead of being frustrated trying to copy and paste from the disappearing instructions

![image](https://user-images.githubusercontent.com/331478/65339578-0198a580-db92-11e9-9d99-f583ab0b6452.png)

**Comment by antonsviridenko** [comment]
fixed by https://github.com/bluecherrydvr/bluecherry-apps/pull/377
