### ISSUE TITLE
Enable VAAPI support for the server.

### ISSUE THREAD

**Issue by rayzorben** [bluecherrydvr/bluecherry-apps#369]
bc-server has vaapi already built-in, but there seem to be no options to enable it from the UI. I am using the released version 2.8.8.

Downloading it from github and compiling myself enables support for VAAPI and seems to be working. My CPU (8 cores, 800% CPU) drops from 210% down to 115% when using VAAPI support.

**Comment by curtishall** [comment]
Correct, VA-API was added into the server for the current branch for testing and further development.  It will significantly reduced CPU usage.

**Comment by rayzorben** [comment]
Would you like feedback? I'm hitting a bug i've been debugging to try to figure out. It happens when motion is detected and it is trying to create the file.

```
Nov 27 15:37:06 . bc-server[342151]: E(1/Front Porch): Error starting device stream: 
Nov 27 15:37:07 . bc-server[342151]: E(1/Front Porch): Failed to init muxer for output file /recordings/2019/11/27/000001/07-22-48.mkv: Invalid data found when processing input (-1094995529)
Nov 27 15:37:07 . bc-server[342151]: E(1/Front Porch): Cannot start recording!
Nov 27 15:37:45 . bc-server[342151]: E(1/Front Porch): Failed to open stream. Error: -1094995529 (Invalid data found when processing input)
```

It is failing in init_muxer in libav

```
Nov 27 15:42:11 raybeastarch bc-server[345888]: D(1/Front Porch): [libav] error Tag [200][127][0][0] incompatible with output codec id '28' (H264)
```

**Comment by antonsviridenko** [comment]
Version 2.8.8 is from stable releases branch 2.8, so only bugfix updates can be expected there. Master branch from git repo contains code for next branch 3.0 which is not officially released yet, it is not considered fully ready for production use, some things may not work as expected there.

**Comment by antonsviridenko** [comment]
> Nov 27 15:42:11 . bc-server[345888]: D(1/Front Porch): [libav] error Tag [200][127][0][0] incompatible with output codec id '28' (H264)

What codec is used for source stream "Front Porch"? Is it H264? Is it an IP camera or capture card?

**Comment by rayzorben** [comment]
@antonsviridenko It is an IP camera, H.264H stream. Issue happens as well with continuous recording.

It fails in init_muxer at this point:

```
  if (par->codec_tag) {
                if (!validate_codec_tag(s, st)) {
                    const uint32_t otag = av_codec_get_tag(s->oformat->codec_tag, par->codec_id);
                    av_log(s, AV_LOG_ERROR,
                           "Tag %s incompatible with output codec id '%d' (%s)\n",
                           av_fourcc2str(par->codec_tag), par->codec_id, av_fourcc2str(otag));
                    ret = AVERROR_INVALIDDATA;
                    goto fail;
                }
```

ffprobe output

```
Input #0, rtsp, from 'rtsp://user:pass@192.168.0.20/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 2592x1520, 100 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 64000 Hz, 1 channels, s16, 512 kb/s

```

**Comment by antonsviridenko** [comment]
Can you please try to revert this commit:
` git revert 421e520c09aaf5082fcfc0eb58427ae447c622f5`
rebuild and check if it works for you?

**Comment by rayzorben** [comment]
Yes, recording works fine after reverting that commit, thanks!

**Comment by antonsviridenko** [comment]
server v3.0.1 is released, with VAAPI support
