### ISSUE TITLE
Add support for docker images

### ISSUE THREAD

**Issue by x-jokay** [bluecherrydvr/bluecherry-apps#378]
Add support for docker images on [hub.docker.com](https://hub.docker.com).

Having the commands from `https://dl.bluecherrydvr.com/scripts/install` and used paths directly in a `Dockerfile` in the official repo and setup [automated builds](https://docs.docker.com/docker-hub/builds/) triggered by commits or releases would be great.

**Comment by curtishall** [comment]
You can play around with this docker image here - https://github.com/bluecherrydvr/bluecherry-docker

I'll work on getting it added to hub.docker.com in the next few weeks.
