### ISSUE TITLE
"err ajax" when trying to get a date range

### ISSUE THREAD

**Issue by brooks-bridges** [bluecherrydvr/bluecherry-apps#388]
I have a default installation of 2.8.8 on Ubuntu 16.04.6 LTS with 5 cameras (Amcrest).  I have no issues with any of the services, except when I try to search a date range, for example 07/15/2020 00:00 through 07/15/2020 23:55, I get a popup with "err ajax" and no other information.

I've tried this with many of the search settings, and nothing except the "Quick Date" dropdown appears to work.  I get the same error in Chrome 84.0.4147.89 and Firefox 78.0.2.

The WWW Log shows this (sanitized) error:

[Fri Jul 24 19:50:13.830046 2020] [:error] [pid 16739] [client 172.21.100.20:56580] PHP Fatal error: Uncaught Error: Call to a member function format() on boolean in /usr/share/bluecherry/www/lib/Helpers.php:106\nStack trace:\n#0 /usr/share/bluecherry/www/ajax/playback.php(58): dateToUnix('07/15/2020 23:5...')\n#1 /usr/share/bluecherry/www/lib/Controller.php(123): playback->postData()\n#2 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start(Object(stdClass))\n#3 /usr/share/bluecherry/www/index.php(14): Route->start()\n#4 {main}\n thrown in /usr/share/bluecherry/www/lib/Helpers.php on line 106, referer: https://cameras.xxxxxxxxx.com:7001/playback

**Comment by brooks-bridges** [comment]
sooooo..... any input on how to make this work correctly?

**Comment by curtishall** [comment]
I'm able to reproduce this in v2.8.8 and v3 (beta).  I'll let you know when this is resolved.

**Comment by curtishall** [comment]
On line 91 in /usr/share/bluecherry/www/lib/Helpers.php

`        $res->format_php = 'm/d/Y h:i A';`

Replace with:

`        $res->format_php = 'm/d/Y H:i A';`

**Comment by brooks-bridges** [comment]
Looks like we're halfway there.  I'm not getting the ajax error anymore, so thank you for that!

I does appear however that we have a 1300 vs 0100 issue.  https://i.imgur.com/IxmGDj0.png

**Comment by brooks-bridges** [comment]
??  Is there a fix for the time not being right when searching?

**Comment by curtishall** [comment]
Yes, this is resolved in 3.0.3. Which distro are you using?

**Comment by curtishall** [comment]
Reassigned to @myjimmy to look into

![Screen Shot 2021-04-14 at 8 30 20 PM](https://user-images.githubusercontent.com/331478/114800926-4bdb0c00-9d60-11eb-9f96-c54291c3f2f1.png)

**Comment by myjimmy** [comment]
closed in commit [#0982f54](https://github.com/bluecherrydvr/bluecherry-apps/commit/c9420d0b54433b7ccdea767d1766fd99a80ba5aa).
