### ISSUE TITLE
Creating rtsp streaming with some objects from opencv's processing 

### ISSUE THREAD

**Issue by hongson23** [bluecherrydvr/bluecherry-apps#404]
Hello @curtishall,
From client, I received source streaming rtsp://Admin:bluecherry@192.168.3.226:7002/live/1 from bluecherry-apps server 
I saw that bluecherry server have processed motion handler with opencv, so I would like to create some objects with opencv and then streaming video with that objects to clients
Can you give me some suggestion?
thanks

**Comment by curtishall** [comment]
Sorry, I can't help you on this.  You are welcome to look at the code and adapt the code to what you need but this is outside the scope of our project.
