### ISSUE TITLE
Unable to Return single image (JPEG) with basic header auth

### ISSUE THREAD

**Issue by ronluna** [bluecherrydvr/bluecherry-apps#418]
When using 
https://login:password@bluecherry-server:7001/media/mjpeg.php?id={camera_id}

to retrieve a single image the browser ignores the credentials entered in the url and ask for login again. This behavior limits the integration with other system to retrieve single images when a full stream is not required. is there away to enable basic header authentication for media/mjpeg.php ?

**Comment by curtishall** [comment]
Are you using port 7001 (https://login:password@host:7001)
?

**Comment by ronluna** [comment]
yes

**Comment by curtishall** [comment]
It seems to work for me to get a MJPEG 

curt@x5:~$ wget --no-check-certificate "https://Admin:bluecherry@192.168.86.39:7001/media/mjpeg.php?id=13"

--2021-04-13 16:56:42--  https://Admin:*password*@192.168.86.39:7001/media/mjpeg.php?id=13
Connecting to 192.168.86.39:7001... connected.
    WARNING: certificate common name ‘x5’ doesn't match requested host name ‘192.168.86.39’.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="Bluecherry"
Connecting to 192.168.86.39:7001... connected.
    WARNING: certificate common name ‘x5’ doesn't match requested host name ‘192.168.86.39’.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [image/jpeg]
Saving to: ‘mjpeg.php?id=13’

mjpeg.php?id=13         [ <=>                ] 149.48K  --.-KB/s    in 0.03s   

2021-04-13 16:56:43 (5.54 MB/s) - ‘mjpeg.php?id=13’ saved [153072]

curt@x5:~$ file mjpeg.php\?id\=13 
mjpeg.php?id=13: JPEG image data, JFIF standard 1.02, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1920x1080, frames 3

**Comment by ronluna** [comment]
there is another basic auth header although We were able to find a quick fix for it when retrieving the devices. 

We had to modify devices.php to read the following on line 11 on ajax/devices.php

`    public function __construct(){
        parent::__construct();
                //$this->chAccess('devices');
                $this->chAccess('basic');
    }`

Otherwise Bluecherry won't accept basic authentication headers. This little problem has been there with since version 2.2 or earlier...

**Comment by ronluna** [comment]
On my end I get the following:

`
wget --no-check-certificate "https://admin:xxxxxxxxx@10.1.10.11:7001/media/mjpeg.php?id=11"
--2021-04-13 18:05:32--  https://admin:*password*@10.1.10.11:7001/media/mjpeg.php?id=11
Connecting to 10.1.11.21:7001... connected.
WARNING: cannot verify 10.1.10.11's certificate, issued by ‘CN=server-name’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘server-name’ doesn't match requested host name ‘10.1.10.11’.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="Bluecherry"
Reusing existing connection to 10.1.10.11:7001.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
`

**Comment by curtishall** [comment]
I tested on 3.0.4, which version are you using?

**Comment by ronluna** [comment]
3.0.4

**Comment by curtishall** [comment]
Ubuntu 18.04 amd64, 3.0.4

**Comment by curtishall** [comment]
We aren't able to reproduce this on test servers.  @myjimmy and myself have tested this

![image](https://user-images.githubusercontent.com/331478/114759066-53c88b00-9d23-11eb-8466-b61d8cd39496.png)

**Comment by ronluna** [comment]
For some reason I had to add the following ReWriteRule in /usr/share/bluecherry/www/.htaccess  to get working.

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

**Comment by myjimmy** [comment]
@ronluna May I close this issue?

**Comment by ronluna** [comment]
Yup!
