### ISSUE TITLE
VAAPI: Always default to 'none' in Performance/connectivity

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#421]
Auto-detection sometimes fails causing customers unneeded headaches when trying to display live video:

https://forums.bluecherrydvr.com/t/bluecherry-gw-security-5080ip-camera-setup/399/3

https://forums.bluecherrydvr.com/t/live-view-not-working/144/35

etc.

**Comment by myjimmy** [comment]
closed in commit [#c9420d0](https://github.com/bluecherrydvr/bluecherry-apps/commit/c9420d0b54433b7ccdea767d1766fd99a80ba5aa).
