### ISSUE TITLE
Define a global G_SUBDOMAIN_API_BASE_URL

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#442]
Define a global config on bluecherry server that name is G_SUBDOMAIN_API_BASE_URL. Value should be proper endpoint address of subdomain provider api (https://domains.bluecherrydvr.com

**Comment by myjimmy** [comment]
@curtishall, I'll add this parameter to the `GlobalSettings `table for global settings. Please let me know your decision.

**Comment by myjimmy** [comment]
I implemented this feature by using the bluecherry.conf file. (https://github.com/bluecherrydvr/bluecherry-apps/commit/2ff4826a2f452c0ffd4f4f627c1ce7213d9a04e9)

**Comment by myjimmy** [comment]
I re-implemented this feature by using database. (b5a1bb92193efedbc7cc82229fa665f6804af331)
