### ISSUE TITLE
Implement getLicenseId function for subdomain ip address management interface.

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#443]
Implement getLicenseId function for subdomain ip address management interface.

https://github.com/tugrul/bluecherry-apps/commit/0c61f9cc417dcfaff5db4b9a6473cdb856abc7ed#diff-37bacb9b7fdc9e404e0dc45293ec885b427b7195b5c51cb7f6af38097775ca18R40-R41

**Comment by myjimmy** [comment]
I implemented this feature. (https://github.com/bluecherrydvr/bluecherry-apps/commit/b2645429467b07e777acce8f534eb84287c046f3)
