### ISSUE TITLE
Implement new announcement / changelog system

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#445]
Announcekit - Added in:

https://github.com/bluecherrydvr/bluecherry-apps/commit/7fe33bfed95e62f16363a7d9c4c09111701e5204

**Comment by myjimmy** [comment]
I implemented this feature.
Please check https://github.com/bluecherrydvr/bluecherry-apps/commit/990972adb34294382930dd102d5deef445ba180e
