### ISSUE TITLE
Bug: System Log link in menu not working (UblockOrigin plugin problem)

### ISSUE THREAD

**Issue by zenon1823** [bluecherrydvr/bluecherry-apps#474]
Just completed fresh install of Bluecherry 3.1.0-rc2 on fresh install/update of Ubuntu 20.04.2-server.
The System Log link in the menu does not load the system log.  If I manually goto https://192.168.**.**:7001/log the System Log displays.  When clicking the "System Log Link" I notice what looks like a refresh of the main screen but it stays on whatever screen it was on.

**Comment by aleksandre12** [comment]
Can you include browser and browser version, because i can't repeat this issue on latest versions of chrome and firefox. Could you please also include frequency of repeat this issue.

**Comment by zenon1823** [comment]
Well you inspired me to do a bit more digging.  I have the issue with both Firefix 89.0.2 and Chrome 91.0.4472.114
But since you said you couldn't recreate it i tried on a vm with the same browser versions and it worked fine.
When i thought about what was in common between the browsers on the affected system was UblockORIGIN

I attached a Ublock log (filtered as only blocked) for all the links in the admin menu.  I'm not a Ublock expert, im not sure what the yellow logs mean, but they dont seem to break anything.  the red log however is the one that is generated when trying to view the log page.

Like i mentioned going directly to YP:7001/log does not trigger the block.

Hope this helps. :)

![Ublock1](https://user-images.githubusercontent.com/55728532/123553395-f1d7c900-d748-11eb-9cfc-6809ad261b0a.JPG)

**Comment by aleksandre12** [comment]
Thanks. It helped very much.

**Comment by curtishall** [comment]
I can reproduce this with Firefox and Windows 10, see link in bluecherry-dev

**Comment by curtishall** [comment]
Workaround added in 3c510b24a067291b1764d0741cdbe69f9d4a6599
