### ISSUE TITLE
HLS stream is unstable

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#487]
Safari (OSX): https://drive.google.com/file/d/1vMYvGfTdYGJoMkluDB5OsGXMWdGulXTv/view
Chrome (OSX): https://drive.google.com/file/d/1390EFsm5EVCj4lfrn-HGfF0lbY2eaAot/view

Windows Chrome: https://drive.google.com/file/d/13mx4bBJ69LApVVsPHDBr84yv_6lxQGls/view

MJPEG works fine (tested using v2):

https://drive.google.com/file/d/13mx4bBJ69LApVVsPHDBr84yv_6lxQGls/view

**Comment by aleksandre12** [comment]
Tried and can't repeat this issue on https://23.236.180.62:7001/liveview. Is there any more info what you can include?

**Comment by iNotMario** [comment]
FWIW, running vlc against https://X:Y@23.236.180.62:7001/hls/1/index.m3u8 results in 12 seconds of playable video, after which it froze. I've found it to be a random occurrence on my internal install. 

It also seems to take an inordinate amount of time for the stream to begin. This seems to be related to the first few segments being 404s. (I suspect the stream to HLS custom http server is a complicated handover)

Related info... audio doesn't work on HLS streams either.

**Comment by curtishall** [comment]
Thanks, we are currently in the process of resolving this bug.

I can build you test packages, which distribution / release are you using?

**Comment by iNotMario** [comment]
I'm actually already running a build based on bb583a413521c8c2ce4267622c401a4762b490ff
I haven't seen much in the commit tree regarding HLS, so i haven't updated just yet.

My comment was only to assert that this issue is repeatable, and suggesting that he might be able to reproduce it using a different media player like VLC. (Also worth watching the network traffic and you'll see a bunch of 404's on port 7003)

**Comment by curtishall** [comment]
Can you try building the latest using the hls_configuration branch?


https://github.com/bluecherrydvr/bluecherry-apps/tree/hls_configuration

**Comment by iNotMario** [comment]
So i compiled it and gave the HLS piece a try. It certainly seemed to work much better for my Android VLC client - particularly when working with long distance ping times. (eg, remote viewing through a reverse proxy or VPN)

Unfortunately, i'm not able to keep this one running, as it breaks all my recording when they hit the drive.
Pretty sure this is related to a library i'm not updating. (libav, maybe)
Updating that library (with `make install') i end up with mpegts format not available, not entirely sure why that would be the case.

If you can make a deb for ubuntu groovy, i can try running your precompiled version.

**Comment by hongson23** [comment]
Hello,

I am using Ubuntu 20, firerox, and  building the latest using the hls_configuration branch
I have a issue when liveview in website with HLS configuartion, MJPEG is OK
![image](https://user-images.githubusercontent.com/4011696/126859402-e701a4e1-d9cc-4987-8b8d-ee44959fc4cf.png)
Can you review it?

**Comment by kala13x** [comment]
Hi @hongson23 

Seems like you tried to play HLS stream just after adding the device. Mostly it needs few seconds to initialize HLS window, so if you just refresh the page manually, playback should start.

**Comment by hongson23** [comment]
Hello @kala13x 
I have just add a video, can you review it? I refreshed the page manually but it didn't work!
https://user-images.githubusercontent.com/4011696/126864691-aaccf316-857e-4b95-a317-65591e0b81d6.mp4

**Comment by kala13x** [comment]
@hongson23 

In video you are not reloading the page, you are pressing play/pause and that will not reload the player.

Can you please change configuration back to HLS, wait 1 min for example and then try to play in live view? 

In inspect element window, there must be HLS links, can you try to play that link with VLC?

Regards,
Sandro

**Comment by hongson23** [comment]
Ok. I will try to test with VLC but you can see I have pressed reload button in url address which is reload the website
Thanks

**Comment by kala13x** [comment]
@hongson23 

Can you please provide details about your os/browser version and which camera are you using?

I will try to reproduce this issue in same environmet

Thanks

**Comment by hongson23** [comment]
I am using Ubuntu 20.04, Firefox browser, and this is my rtsp livestream
rtsp://admin:abcd1234@@14.241.41.0:1554/media/video1
Can you help me review my environment? Thanks

**Comment by kala13x** [comment]
@hongson23 

Thank you, will try to repeat same issue this evening

**Comment by kala13x** [comment]
@hongson23 

I just finished setup exactly the same environment and tried to play the RTSP stream with the link you provided, but I was unable to repeat the same issue.

I recorded the video so you can see HLS is playable with me from LiveView
https://drive.google.com/file/d/1WEYfL6hBt7PP6HeLxNPCeP112THaKwdD/view?usp=sharing

Maybe you need to update your Firefox browser, I don't have another idea...

**Comment by hongson23** [comment]
Thank you very much!
I updated the fire-fox and it worked correctly!
but I have 2 test cases
1. Try to use another rtsp-streaming: rtsp://admin:abcd1234@113.176.108.56:554
==> hls in web view did not work! 
2.  Try to use gg chrome to play hls so some frame is corrupted
I have just captured a video 
https://drive.google.com/file/d/1mG1VB78h79Gt7kqPyD_HVoeQNtzzlL4q/view 
please take a look, thanks

**Comment by hongson23** [comment]
"Try to use gg chrome to play hls so some frame is corrupted"
==> I tested on firefox browser via IP so some frames were still corrupted!   
It seem to be not related to browser. Maybe it related to view website via IP
thanks

**Comment by kala13x** [comment]
@hongson23 

This link is not working with me at all
rtsp://admin:abcd1234@113.176.108.56:554

Tried with VLC and FFPLAY but the stream is not playable

**Comment by hongson23** [comment]
I have just play and rtsp://admin:abcd1234@113.176.108.56:554 is working 


https://user-images.githubusercontent.com/4011696/126974537-d6dfbc59-a247-4cc1-b7f8-ee43e0ea07f1.mp4

**Comment by hongson23** [comment]
and you can see bluecherry-client can play this livestream which is created by bc-server

https://user-images.githubusercontent.com/4011696/126975465-512284cb-6797-41aa-8d43-5b2521bb0f41.mp4


 

https://user-images.githubusercontent.com/4011696/126975445-d127a8a7-1698-411a-9270-29faebe50006.mp4

**Comment by kala13x** [comment]
@hongson23 

Can you show me screenshot of properties of this IP Camera from the Devices page?

**Comment by hongson23** [comment]
This is screenshot of properties of this IP Camera
please take a look
![image](https://user-images.githubusercontent.com/4011696/126975791-999ceee0-cb2f-460c-a8f1-35844393766b.png)

**Comment by kala13x** [comment]
@hongson23 

To fix corrupted frames for Camera1 please increase HLS segment size by two times for camera1 and try again, it helped with me.

As I guess the second camera is HEVC and I played the HLS stream of this camera in VLC without the problems with exactly the same configurations. 

While playing/trying to play the second camera in LiveView please open inspect element window and open the network tab, you must see get request like: https://127.0.0.1:7001/hls/1/0/playlist.m3u8?authtoken=tdc39m5cf72s94llrk4eognhjk

please copy this link (it will be different for you) and try to play in VLC, if it's playable in VLC or any other players, then we can exclude bc-server side problems and we can ask out front and developer to implement HEVC in HLS.js

Regards,
Sandro

**Comment by hongson23** [comment]
thank for your reply! 
I tried to use VLC play m3u8 follow your suggestion and it works well so bc-server is good for generated hls-streaming  
I will create a issue about hls.js in front-end
thank you very much!
https://user-images.githubusercontent.com/4011696/126978769-9c01d73a-3d39-40f0-85ca-02d78d75aec2.mp4

**Comment by hongson23** [comment]
@kala13x 
To fix corrupted frames for Camera1 please increase HLS segment size by two times for camera1 and try again, it helped with me.
==> Currently I set HLS segment size = 1347584(default) * 2  = 2695168 or 1347584*4 but it is not working for me, some frames often are corrupted!

**Comment by hongson23** [comment]
But when i use VLC to play the same https://127.0.0.1:7001/hls/1/0/playlist.m3u8?authtoken=tdc39m5cf72s94llrk4eognhjk 
all frame are good. I think that is problem of the hls.js

**Comment by kala13x** [comment]
@hongson23 

Yes, I'm debugging always with VLC to exclude server-side problems, thas why it was working with me without flaws.

**Comment by iNotMario** [comment]
Ok, finally got a chance to fully test 8ed692d851110afac47afe2144b8a5bf814ef302
HLS Streams that work do seem substantially more stable, and load much faster.

However... has any testing been done with audio? Cameras that record audio do not seem to work correctly with the HLS streams. VLC indicates basically an endless barrage of dropped frames, in addition to not recognizing the audio channel.
Video-only cameras work great, though.

Hard to know if it's directly correlated, but the cameras with audio also now fail to record; "Failed to init muxer for output file X: Invalid Argument (-22)". These cameras are working in the official release.
