### ISSUE TITLE
Support Re-encoding streaming features on Nvidia 1050Ti  ?

### ISSUE THREAD

**Issue by hongson23** [bluecherrydvr/bluecherry-apps#502]
Hello @kala13x 
I have a question related to hardware video acceleration in re-encoding features
Because bluecherry app only support re-encoding via vaapi with GPU so I tried to use bluecherry with Intel chipset  and its OK
but right now I am using Nvidia card base on Ubuntu which is install nvidia driver 460.91.03-0ubuntu0.20.04.1  
So System log is:  "VAAPI VAAPI device is not initialized!"

Can you any suggestion for me? I read some information in https://wiki.debian.org/HardwareVideoAcceleration so it seem to be not support VAAPI on Nvidia driver ?

Thank you so much!

**Comment by hongson23** [comment]
hello @curtishall 
Can someone help me with this problem?
thanks

**Comment by budgie05** [comment]
Are you using the proprietary or open source nvidia driver.

 `VA-API - Supported on Intel, AMD, and NVIDIA (only via the open-source Nouveau drivers).`

**Comment by hongson23** [comment]
Thank for your confirmation, @budgie05 
I need to use NVIDIA driver for some features which were running on my PC so I will deploy bluecherry server on the other PC

thanks
