### ISSUE TITLE
Debian Buster - Still at 3.1.0-rc2-busterfix

### ISSUE THREAD

**Issue by tenpin784** [bluecherrydvr/bluecherry-apps#532]
Is there a way to get a server running Debian Buster to go beyond the rc2-busterfix? 

I had tried to manually go beyond it, but it was marking RC3/4/5 as a downgrade to it, so I wasn't sure if I should just leave it where it is. The reason for the question is because I am trying to go beyond four cameras during the trial, but I am hitting the bug.

**Comment by curtishall** [comment]
Thanks for the report, I think I resolved the problem now.

Package: bluecherry
Architecture: amd64
Version: 3:3.1.0-rc5
Priority: optional
Section: admin
Maintainer: Bluecherry <maintainers@bluecherrydvr.com>
Installed-Size: 21255
Pre-Depends: adduser
Depends: libbsd0 (>= 0.0), libc6 (>= 2.28), libgcc1 (>= 1:3.0), libmariadb3 (>= 3.0.0), libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.26), libopencv-core3.2, libopencv-imgcodecs3.2, libopencv-imgproc3.2, libstdc++6 (>= 6), libudev1 (>= 183), libva-drm2 (>= 1.1.0), libva2 (>= 2.2.0), zlib1g (>= 1:1.2.0.2), ssl-cert, ucf, curl, sysstat, mkvtoolnix, php-mail, php-mail-mime, php-net-smtp, sqlite3, nmap, nginx, php-fpm, php-mysql, php-sqlite3, v4l-utils, vainfo, i965-va-driver, python3-pip, php-gd, php-curl
Recommends: mysql-server
Suggests: monit, mail-transport-agent
Conflicts: solo6010-dkms
Replaces: solo6010-dkms
Filename: pool/buster/bluecherry_3.1.0-rc5_amd64.deb
Size: 5269552
MD5sum: bd89f8515ebfa9b2c39717f4be28dfe5
SHA1: de9d505f136e3dbba3144bc25665420f119fbb42
SHA256: b14f5dc5298bddd999a74a2d8eaa45e9fca28219d289c11be2e909d506578fa1
SHA512: 0fc567f52574612c68a0177f6d071281d0efd02bdf7e17b8087d3af7488287bf82be744ea0ddfc2d738ea512df28bd24a4f71b3d70404bdc150b5e33e57de3f4
Description: Bluecherry DVR Server
 This package contains the server components for the Bluecherry DVR system.

**Comment by tenpin784** [comment]
Fixed for me! Thanks!
