### ISSUE TITLE
Build error of v3.1.0-rc5

### ISSUE THREAD

**Issue by myjimmy** [bluecherrydvr/bluecherry-apps#535]
When building the `master` branch, I get the following error:
```
scripts/install_prereqs_native.sh: line 49: syntax error near unexpected token `<<<'
```

I found the following issue in `scripts/install_prereqs_native.sh` file:
![image](https://user-images.githubusercontent.com/52309150/170395842-21440a2c-0932-40a4-808e-294ad574709a.png)

It seems that somebody made the mistake when resolving some conflicts.

Thanks.

**Comment by myjimmy** [comment]
@curtishall I've fixed this issue.
I've just submitted a PR: https://github.com/bluecherrydvr/bluecherry-apps/pull/536

**Comment by curtishall** [comment]
Thanks!
