### ISSUE TITLE
Storage does not always respect setting default (/var/lib/bluecherry/recordings)

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#656]
In this test setup on .66 /var/lib/bluecherry/recordings is set to a max of 15% with a 100GB partition.  After configuring 256 devices 100% of the disk is used.

I'm not sure if this is related to disk cleanup failing with so many devices or not, however it appears to work mostly fine on /mnt/store (100gb partition) which has priority=1 with max set at 95%.

**Comment by andrey-utkin** [comment]
The situation is no longer observable on that host.
PR #677 (just merged) hopefully fixes it.
