### ISSUE TITLE
Serious memory leaks with 3.1.2

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#693]
Multiple reports here: https://forums.bluecherrydvr.com/t/memory-leak-after-update-to-3-1-2-on-ubuntu-22lts/905/6

https://ffmpeg.org//pipermail/ffmpeg-devel/2024-May/326569.html

Recommendation: Upgrade to ffmpeg 6.1.2

**Comment by andrey-utkin** [comment]
fixed by #694
